[package]
name = "spallcomp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifier = "0.2.1"
include_dir = { version = "0.7.2", features = ["glob"] }
derive_more = "0.99.17"